work_options:
  mode: patch
  commitId: 9b7c2a074bfbf22256b3728629182fe9686c9773  #Id of commit after that we look for changed objects including
  path:
    installDir: e:\WorkSpace\TCS_Oracle\install\2022ww51-02\ # directory where we will put install files
    rootDir: e:\Workspace\TCS_oracle\ # directory from where we get oracle objects