work_options:
  mode: patch
  commitId: b058ffd00f7b17ce4b085920860f9433bac23be2 #Id of commit after that we look for changed objects including
  path:
    installDir: e:\WorkSpace\TCS_Oracle\install\2023ww03-04\ # directory where we will put install files
    rootDir: e:\WorkSpace\TCS_Oracle\ # directory from where we get oracle objects