work_options:
  mode: patch
  commitId: a19d91b20d7e7cf9f57578c41e3c8481d7dbe993 #Id of commit after that we look for changed objects including
  path:
    installDir: e:\WorkSpace\tj-oracle\install\2023ww09-10\ # directory where we will put install files
    rootDir: e:\WorkSpace\tj-oracle\ # directory from where we get oracle objects